### PR TITLE
Cleanup default game template

### PR DESCRIPTION
**Pull request by morganwillcock**
Mostly just tidying up, and small fixes, plus a (mostly) rewritten keyboard movement script which removes a lot of duplicate code and the use of separate keys to move diagonally or stop.

### CODE REVIEW

**Comment by ivan-mogilko** [comment]
Does this brings an update from https://github.com/caesarcub/AGS-SCI-Template ?

I would like to suggest to rename this template to "Sierra-like" or similar (I did this for 3.4.1 p2 distribution).

**Comment by ivan-mogilko** [comment]
Hmm. AGS requires to type in a name each time you create template from the game project, so it's not defined anywhere. Perhaps the game folder should be renamed.

**Comment by morganwillcock** [comment]
It looks like when you choose to export it as a template it prompts for a name, which defaults to an empty text input. I think for building a game you would have to rename the folder, but did you just enter "Sierra-like" as the name when you exported it for the other release?

Strangely, it doesn't let me export a template. I get the message "There was an error creating your template: ERROR: unable to open file for writing".

**Comment by ivan-mogilko** [comment]
>  I think for building a game you would have to rename the folder, but did you just enter "Sierra-like" as the name when you exported it for the other release?

Yes, I simply opened Caesar Cub's project and named it "Sierra-style".

The name of the folder is not automatically defining template's name, but it may serve as an indication of how this template should be called when someone manages the distribution.

**Pull request merged**
