### PR TITLE
Fixed transparency on sprite 2008

### PR DESCRIPTION
**Pull request by monkey0506**
Export and reimport of the sprite fixed the problem.

### CODE REVIEW

**Comment by ivan-mogilko** [comment]
I have discovered an issue with how templates repository is being used by automatic build server.
In the nutshell, there were no distinction between package versions. Until that is resolved it's better not to push anything here.

Also, we need to find out which version was this transparency problem introduced first. If you update repository you may notice there should be 3 branches now, with release-3.3.5 and release-3.4.0 added recently. I have a guess that this bug may be found since 3.3.5, in which case this fix should be done in that branch first.

**Comment by monkey0506** [comment]
Fair enough. I guess hiccups are to be expected as things like this get introduced. Should I close this and reopen it on a specific branch?

**Comment by ivan-mogilko** [comment]
I do not remember if github allows to switch pull request branch yet? If it still does not, then closing and reopening is the only way.

**Comment by ivan-mogilko** [comment]
Duh, apparently not....
https://github.com/isaacs/github/issues/18

**Comment by monkey0506** [comment]
I was just reading that (top result in Google). 3+ years and no way to change the target of the PR on Github. Ah, well. Will try to track down where this originated and recreate it as appropriate.

**Comment by ivan-mogilko** [comment]
Ouch, pfff, I mistook one repository for another. We have "templates" and "template-source" repositories, and I created those branches for "templates", but forgot to do same for "template-source".
Will do that now.

**Comment by ivan-mogilko** [comment]
@monkey0506 , I hope you don't mind, I just took your commit and pushed it into the 3.3.5 branch, so the pull request is no longer necessary.

**Pull request closed without merging**
